package com.example.model

/**
 * Real-world Distribution Transformer & Substation Node across Nigeria
 */
data class NigeriaTransformer(
    val id: String,
    val name: String,
    val street: String,
    val city: String,
    val state: String,
    val discoCode: String,
    val feederName: String,
    val feederBand: FeederBand,
    val latitude: Double,
    val longitude: Double,
    val capacityKva: Int,
    val loadPercent: Int,
    val phaseAVolts: Int,
    val phaseBVolts: Int,
    val phaseCVolts: Int,
    val connectedHouseholds: Int,
    val status: TransformerStatus,
    val oilTempCelsius: Int,
    val humSparkRisk: String,
    val failureCountMonth: Int = 0,
    val missingPartNotice: String? = null
)

enum class TransformerStatus(val label: String, val colorHex: Long) {
    HEALTHY("Operational / Balanced", 0xFF22C55E),
    HEAVY_LOAD("Heavy Load (75-89%)", 0xFFF59E0B),
    OVERLOADED("Critical Overload (90%+)", 0xFFEF4444),
    FAULT_TRIPPED("Blown / Tripped Down", 0xFFDC2626),
    LOAD_SHEDDING("Load Shedding (TCN Quota)", 0xFF8B5CF6)
}

object NigeriaTransformerRegistry {
    val ALL_TRANSFORMERS = listOf(
        // LAGOS STATE (EKEDC & IE)
        NigeriaTransformer(
            id = "TR-LOS-VI-04B",
            name = "Adeola Odeku 500kVA Distribution Substation",
            street = "14 Adeola Odeku Street, Victoria Island",
            city = "Lagos",
            state = "Lagos State",
            discoCode = "EKEDC",
            feederName = "Victoria Island 33kV Injection Feeder 4",
            feederBand = FeederBand.BAND_A,
            latitude = 6.4281,
            longitude = 3.4219,
            capacityKva = 500,
            loadPercent = 88,
            phaseAVolts = 236,
            phaseBVolts = 182,
            phaseCVolts = 239,
            connectedHouseholds = 184,
            status = TransformerStatus.HEAVY_LOAD,
            oilTempCelsius = 74,
            humSparkRisk = "High (Phase B Coil Heat)",
            failureCountMonth = 1,
            missingPartNotice = null
        ),
        NigeriaTransformer(
            id = "TR-LOS-IKJ-11",
            name = "Allen Avenue Commercial 750kVA Substation",
            street = "Allen Avenue, Ikeja",
            city = "Ikeja",
            state = "Lagos State",
            discoCode = "IE",
            feederName = "Alausa 33kV Express Feeder 2",
            feederBand = FeederBand.BAND_A,
            latitude = 6.6018,
            longitude = 3.3515,
            capacityKva = 750,
            loadPercent = 95,
            phaseAVolts = 210,
            phaseBVolts = 195,
            phaseCVolts = 205,
            connectedHouseholds = 310,
            status = TransformerStatus.OVERLOADED,
            oilTempCelsius = 86,
            humSparkRisk = "Critical Arc Flash Warning",
            failureCountMonth = 3,
            missingPartNotice = "Requires 630A LV Breaker Core"
        ),
        NigeriaTransformer(
            id = "TR-LOS-LEK-02",
            name = "Admiralty Way 500kVA Distribution Unit",
            street = "Admiralty Way, Lekki Phase 1",
            city = "Lekki",
            state = "Lagos State",
            discoCode = "EKEDC",
            feederName = "Lekki Expressway 33kV Line",
            feederBand = FeederBand.BAND_A,
            latitude = 6.4474,
            longitude = 3.4723,
            capacityKva = 500,
            loadPercent = 64,
            phaseAVolts = 232,
            phaseBVolts = 230,
            phaseCVolts = 234,
            connectedHouseholds = 142,
            status = TransformerStatus.HEALTHY,
            oilTempCelsius = 58,
            humSparkRisk = "Nominal",
            failureCountMonth = 0,
            missingPartNotice = null
        ),
        NigeriaTransformer(
            id = "TR-LOS-SUR-09",
            name = "Bode Thomas Residential 300kVA Transformer",
            street = "Bode Thomas Street, Surulere",
            city = "Surulere",
            state = "Lagos State",
            discoCode = "EKEDC",
            feederName = "Itire 11kV Feeder",
            feederBand = FeederBand.BAND_B,
            latitude = 6.4969,
            longitude = 3.3553,
            capacityKva = 300,
            loadPercent = 92,
            phaseAVolts = 218,
            phaseBVolts = 215,
            phaseCVolts = 220,
            connectedHouseholds = 198,
            status = TransformerStatus.OVERLOADED,
            oilTempCelsius = 82,
            humSparkRisk = "Moderate Hum",
            failureCountMonth = 2,
            missingPartNotice = "400A HRC Fuses (Store Requisition)"
        ),
        NigeriaTransformer(
            id = "TR-LOS-MAR-01",
            name = "Broad Street Commercial 1000kVA Substation",
            street = "Broad Street, Lagos Island",
            city = "Lagos",
            state = "Lagos State",
            discoCode = "EKEDC",
            feederName = "Marina 33kV Dedicated Loop",
            feederBand = FeederBand.BAND_A,
            latitude = 6.4531,
            longitude = 3.3958,
            capacityKva = 1000,
            loadPercent = 48,
            phaseAVolts = 238,
            phaseBVolts = 236,
            phaseCVolts = 237,
            connectedHouseholds = 85,
            status = TransformerStatus.HEALTHY,
            oilTempCelsius = 52,
            humSparkRisk = "Nominal",
            failureCountMonth = 0,
            missingPartNotice = null
        ),
        NigeriaTransformer(
            id = "TR-LOS-YAB-06",
            name = "Herbert Macaulay Tech 500kVA Unit",
            street = "Herbert Macaulay Way, Yaba",
            city = "Yaba",
            state = "Lagos State",
            discoCode = "IE",
            feederName = "Akoka 11kV Feeder",
            feederBand = FeederBand.BAND_B,
            latitude = 6.5167,
            longitude = 3.3789,
            capacityKva = 500,
            loadPercent = 78,
            phaseAVolts = 226,
            phaseBVolts = 224,
            phaseCVolts = 229,
            connectedHouseholds = 220,
            status = TransformerStatus.HEAVY_LOAD,
            oilTempCelsius = 66,
            humSparkRisk = "Low Hum",
            failureCountMonth = 0,
            missingPartNotice = null
        ),
        NigeriaTransformer(
            id = "TR-LOS-IKD-03",
            name = "Ikorodu Town 300kVA Substation",
            street = "Sagamu Road, Ikorodu",
            city = "Ikorodu",
            state = "Lagos State",
            discoCode = "IE",
            feederName = "Ikorodu 33kV Injection Station",
            feederBand = FeederBand.BAND_C,
            latitude = 6.6194,
            longitude = 3.5105,
            capacityKva = 300,
            loadPercent = 98,
            phaseAVolts = 0,
            phaseBVolts = 0,
            phaseCVolts = 0,
            connectedHouseholds = 240,
            status = TransformerStatus.FAULT_TRIPPED,
            oilTempCelsius = 95,
            humSparkRisk = "Blown Bushing Failure",
            failureCountMonth = 4,
            missingPartNotice = "Burnt HV Bushing & 50L Dielectric Oil"
        ),

        // ABUJA / FCT (AEDC)
        NigeriaTransformer(
            id = "TR-ABJ-MAI-03",
            name = "Maitama Diplomatic 1000kVA Substation",
            street = "Gana Street, Maitama",
            city = "Abuja",
            state = "Abuja FCT",
            discoCode = "AEDC",
            feederName = "Maitama 33kV Feeder 1",
            feederBand = FeederBand.BAND_A,
            latitude = 9.0882,
            longitude = 7.4934,
            capacityKva = 1000,
            loadPercent = 42,
            phaseAVolts = 235,
            phaseBVolts = 234,
            phaseCVolts = 236,
            connectedHouseholds = 110,
            status = TransformerStatus.HEALTHY,
            oilTempCelsius = 49,
            humSparkRisk = "Nominal",
            failureCountMonth = 0,
            missingPartNotice = null
        ),
        NigeriaTransformer(
            id = "TR-ABJ-WUS-08",
            name = "Wuse II Commercial 750kVA Transformer",
            street = "Aminu Kano Crescent, Wuse II",
            city = "Abuja",
            state = "Abuja FCT",
            discoCode = "AEDC",
            feederName = "Wuse 33kV Express Feeder",
            feederBand = FeederBand.BAND_A,
            latitude = 9.0765,
            longitude = 7.4721,
            capacityKva = 750,
            loadPercent = 93,
            phaseAVolts = 212,
            phaseBVolts = 208,
            phaseCVolts = 214,
            connectedHouseholds = 290,
            status = TransformerStatus.OVERLOADED,
            oilTempCelsius = 84,
            humSparkRisk = "Audible 50Hz Heavy Resonance",
            failureCountMonth = 2,
            missingPartNotice = "Awaiting Load Relief Substation"
        ),
        NigeriaTransformer(
            id = "TR-ABJ-GAR-14",
            name = "Garki II Area 500kVA Distribution Unit",
            street = "Tafawa Balewa Way, Garki II",
            city = "Abuja",
            state = "Abuja FCT",
            discoCode = "AEDC",
            feederName = "Garki 11kV Feeder 3",
            feederBand = FeederBand.BAND_A,
            latitude = 9.0345,
            longitude = 7.4891,
            capacityKva = 500,
            loadPercent = 84,
            phaseAVolts = 224,
            phaseBVolts = 220,
            phaseCVolts = 228,
            connectedHouseholds = 205,
            status = TransformerStatus.HEAVY_LOAD,
            oilTempCelsius = 71,
            humSparkRisk = "Nominal",
            failureCountMonth = 1,
            missingPartNotice = null
        ),
        NigeriaTransformer(
            id = "TR-ABJ-CBD-01",
            name = "CBD Central 1500kVA Transmission Stepdown",
            street = "Constitution Avenue, Central Business District",
            city = "Abuja",
            state = "Abuja FCT",
            discoCode = "AEDC",
            feederName = "Abuja 132/33kV Central Injection",
            feederBand = FeederBand.BAND_A,
            latitude = 9.0579,
            longitude = 7.4951,
            capacityKva = 1500,
            loadPercent = 38,
            phaseAVolts = 239,
            phaseBVolts = 238,
            phaseCVolts = 240,
            connectedHouseholds = 65,
            status = TransformerStatus.HEALTHY,
            oilTempCelsius = 44,
            humSparkRisk = "Nominal",
            failureCountMonth = 0,
            missingPartNotice = null
        ),
        NigeriaTransformer(
            id = "TR-ABJ-GWA-22",
            name = "Gwarinpa Estate 500kVA Substation",
            street = "1st Avenue, Gwarinpa Estate",
            city = "Abuja",
            state = "Abuja FCT",
            discoCode = "AEDC",
            feederName = "Kubwa-Gwarinpa 33kV Feeder",
            feederBand = FeederBand.BAND_B,
            latitude = 9.1097,
            longitude = 7.4112,
            capacityKva = 500,
            loadPercent = 82,
            phaseAVolts = 225,
            phaseBVolts = 221,
            phaseCVolts = 226,
            connectedHouseholds = 230,
            status = TransformerStatus.HEAVY_LOAD,
            oilTempCelsius = 68,
            humSparkRisk = "Low Hum",
            failureCountMonth = 1,
            missingPartNotice = null
        ),

        // PORT HARCOURT / RIVERS (PHED)
        NigeriaTransformer(
            id = "TR-PHC-GRA-05",
            name = "Old GRA 500kVA Distribution Substation",
            street = "Forces Avenue, Old GRA",
            city = "Port Harcourt",
            state = "Rivers State",
            discoCode = "PHED",
            feederName = "Secretariat 33kV Feeder",
            feederBand = FeederBand.BAND_A,
            latitude = 4.8156,
            longitude = 7.0123,
            capacityKva = 500,
            loadPercent = 56,
            phaseAVolts = 230,
            phaseBVolts = 228,
            phaseCVolts = 232,
            connectedHouseholds = 120,
            status = TransformerStatus.HEALTHY,
            oilTempCelsius = 54,
            humSparkRisk = "Nominal",
            failureCountMonth = 0,
            missingPartNotice = null
        ),
        NigeriaTransformer(
            id = "TR-PHC-TRA-02",
            name = "Trans Amadi Industrial 1000kVA Station",
            street = "Trans Amadi Industrial Layout",
            city = "Port Harcourt",
            state = "Rivers State",
            discoCode = "PHED",
            feederName = "Trans Amadi 33kV Heavy Line",
            feederBand = FeederBand.BAND_A,
            latitude = 4.8256,
            longitude = 7.0392,
            capacityKva = 1000,
            loadPercent = 86,
            phaseAVolts = 222,
            phaseBVolts = 219,
            phaseCVolts = 225,
            connectedHouseholds = 75,
            status = TransformerStatus.HEAVY_LOAD,
            oilTempCelsius = 72,
            humSparkRisk = "Low Vibration",
            failureCountMonth = 1,
            missingPartNotice = null
        ),
        NigeriaTransformer(
            id = "TR-PHC-DLN-17",
            name = "D-Line Residential 300kVA Transformer",
            street = "Olu Obasanjo Road, D-Line",
            city = "Port Harcourt",
            state = "Rivers State",
            discoCode = "PHED",
            feederName = "Garrison 11kV Feeder",
            feederBand = FeederBand.BAND_B,
            latitude = 4.8091,
            longitude = 7.0019,
            capacityKva = 300,
            loadPercent = 97,
            phaseAVolts = 0,
            phaseBVolts = 0,
            phaseCVolts = 0,
            connectedHouseholds = 265,
            status = TransformerStatus.FAULT_TRIPPED,
            oilTempCelsius = 98,
            humSparkRisk = "Jumper Snapped & Cable Arc",
            failureCountMonth = 3,
            missingPartNotice = "120mm² Aluminum Jumper & Clamps"
        ),

        // IBADAN / OYO (IBEDC)
        NigeriaTransformer(
            id = "TR-IBD-BOD-07",
            name = "Bodija Residential 500kVA Substation",
            street = "Secretariat Road, Bodija",
            city = "Ibadan",
            state = "Oyo State",
            discoCode = "IBEDC",
            feederName = "Bodija 33kV Line",
            feederBand = FeederBand.BAND_A,
            latitude = 7.4243,
            longitude = 3.9056,
            capacityKva = 500,
            loadPercent = 72,
            phaseAVolts = 228,
            phaseBVolts = 226,
            phaseCVolts = 230,
            connectedHouseholds = 175,
            status = TransformerStatus.HEALTHY,
            oilTempCelsius = 62,
            humSparkRisk = "Nominal",
            failureCountMonth = 0,
            missingPartNotice = null
        ),
        NigeriaTransformer(
            id = "TR-IBD-DUG-03",
            name = "Dugbe Commercial 750kVA Unit",
            street = "Cocoa House Area, Dugbe",
            city = "Ibadan",
            state = "Oyo State",
            discoCode = "IBEDC",
            feederName = "Dugbe Central 11kV Feeder",
            feederBand = FeederBand.BAND_A,
            latitude = 7.3889,
            longitude = 3.8792,
            capacityKva = 750,
            loadPercent = 68,
            phaseAVolts = 231,
            phaseBVolts = 229,
            phaseCVolts = 233,
            connectedHouseholds = 190,
            status = TransformerStatus.HEALTHY,
            oilTempCelsius = 59,
            humSparkRisk = "Nominal",
            failureCountMonth = 0,
            missingPartNotice = null
        ),
        NigeriaTransformer(
            id = "TR-IBD-RNG-12",
            name = "Ring Road 500kVA Transformer",
            street = "Ring Road Expressway, Ibadan",
            city = "Ibadan",
            state = "Oyo State",
            discoCode = "IBEDC",
            feederName = "Ring Road 33kV Injection",
            feederBand = FeederBand.BAND_B,
            latitude = 7.3621,
            longitude = 3.8643,
            capacityKva = 500,
            loadPercent = 91,
            phaseAVolts = 214,
            phaseBVolts = 208,
            phaseCVolts = 218,
            connectedHouseholds = 245,
            status = TransformerStatus.OVERLOADED,
            oilTempCelsius = 81,
            humSparkRisk = "Audible Strain Buzz",
            failureCountMonth = 2,
            missingPartNotice = "Overload Relief Needed"
        ),

        // ENUGU / ENUGU (EEDC)
        NigeriaTransformer(
            id = "TR-ENU-IND-01",
            name = "Independence Layout 500kVA Substation",
            street = "Okpara Avenue, Independence Layout",
            city = "Enugu",
            state = "Enugu State",
            discoCode = "EEDC",
            feederName = "Independence 33kV Feeder",
            feederBand = FeederBand.BAND_A,
            latitude = 6.4421,
            longitude = 7.5142,
            capacityKva = 500,
            loadPercent = 61,
            phaseAVolts = 230,
            phaseBVolts = 228,
            phaseCVolts = 232,
            connectedHouseholds = 135,
            status = TransformerStatus.HEALTHY,
            oilTempCelsius = 55,
            humSparkRisk = "Nominal",
            failureCountMonth = 0,
            missingPartNotice = null
        ),
        NigeriaTransformer(
            id = "TR-ENU-NEW-08",
            name = "New Haven 300kVA Transformer",
            street = "Chime Avenue, New Haven",
            city = "Enugu",
            state = "Enugu State",
            discoCode = "EEDC",
            feederName = "New Haven 11kV Line",
            feederBand = FeederBand.BAND_B,
            latitude = 6.4518,
            longitude = 7.5312,
            capacityKva = 300,
            loadPercent = 94,
            phaseAVolts = 0,
            phaseBVolts = 0,
            phaseCVolts = 0,
            connectedHouseholds = 210,
            status = TransformerStatus.LOAD_SHEDDING,
            oilTempCelsius = 42,
            humSparkRisk = "De-energized for TCN Quota",
            failureCountMonth = 1,
            missingPartNotice = null
        ),

        // KANO STATE (KEDCO)
        NigeriaTransformer(
            id = "TR-KAN-NAS-04",
            name = "Nasarawa GRA 750kVA Substation",
            street = "State Road, Nasarawa GRA",
            city = "Kano",
            state = "Kano State",
            discoCode = "KEDCO",
            feederName = "Nasarawa 33kV Express",
            feederBand = FeederBand.BAND_A,
            latitude = 11.9964,
            longitude = 8.5392,
            capacityKva = 750,
            loadPercent = 58,
            phaseAVolts = 232,
            phaseBVolts = 230,
            phaseCVolts = 234,
            connectedHouseholds = 160,
            status = TransformerStatus.HEALTHY,
            oilTempCelsius = 52,
            humSparkRisk = "Nominal",
            failureCountMonth = 0,
            missingPartNotice = null
        ),
        NigeriaTransformer(
            id = "TR-KAN-BOM-01",
            name = "Bompai Industrial 1000kVA Station",
            street = "Bompai Industrial Layout",
            city = "Kano",
            state = "Kano State",
            discoCode = "KEDCO",
            feederName = "Bompai 33kV Heavy Line",
            feederBand = FeederBand.BAND_B,
            latitude = 12.0125,
            longitude = 8.5614,
            capacityKva = 1000,
            loadPercent = 84,
            phaseAVolts = 224,
            phaseBVolts = 220,
            phaseCVolts = 228,
            connectedHouseholds = 95,
            status = TransformerStatus.HEAVY_LOAD,
            oilTempCelsius = 73,
            humSparkRisk = "Low Hum",
            failureCountMonth = 1,
            missingPartNotice = null
        ),

        // KADUNA STATE (KAEDC)
        NigeriaTransformer(
            id = "TR-KAD-BAR-09",
            name = "Barnawa High Cost 500kVA Substation",
            street = "Barnawa Road, Kaduna South",
            city = "Kaduna",
            state = "Kaduna State",
            discoCode = "KAEDC",
            feederName = "Barnawa 33kV Line",
            feederBand = FeederBand.BAND_B,
            latitude = 10.4856,
            longitude = 7.4241,
            capacityKva = 500,
            loadPercent = 76,
            phaseAVolts = 227,
            phaseBVolts = 225,
            phaseCVolts = 229,
            connectedHouseholds = 180,
            status = TransformerStatus.HEALTHY,
            oilTempCelsius = 64,
            humSparkRisk = "Nominal",
            failureCountMonth = 0,
            missingPartNotice = null
        ),

        // BENIN CITY / EDO (BEDC)
        NigeriaTransformer(
            id = "TR-BEN-GRA-06",
            name = "Benin GRA 500kVA Substation",
            street = "Boundary Road, GRA",
            city = "Benin City",
            state = "Edo State",
            discoCode = "BEDC",
            feederName = "Airport Road 33kV Feeder",
            feederBand = FeederBand.BAND_A,
            latitude = 6.3176,
            longitude = 5.6145,
            capacityKva = 500,
            loadPercent = 71,
            phaseAVolts = 229,
            phaseBVolts = 226,
            phaseCVolts = 231,
            connectedHouseholds = 150,
            status = TransformerStatus.HEALTHY,
            oilTempCelsius = 60,
            humSparkRisk = "Nominal",
            failureCountMonth = 0,
            missingPartNotice = null
        ),

        // JOS / PLATEAU (JED)
        NigeriaTransformer(
            id = "TR-JOS-RAY-02",
            name = "Rayfield Residential 500kVA Transformer",
            street = "Old Airport Road, Rayfield",
            city = "Jos",
            state = "Plateau State",
            discoCode = "JED",
            feederName = "Rayfield 33kV Line",
            feederBand = FeederBand.BAND_A,
            latitude = 9.8512,
            longitude = 8.8924,
            capacityKva = 500,
            loadPercent = 54,
            phaseAVolts = 233,
            phaseBVolts = 231,
            phaseCVolts = 235,
            connectedHouseholds = 125,
            status = TransformerStatus.HEALTHY,
            oilTempCelsius = 48,
            humSparkRisk = "Nominal",
            failureCountMonth = 0,
            missingPartNotice = null
        ),

        // CALABAR / CROSS RIVER (PHED)
        NigeriaTransformer(
            id = "TR-CAL-MAR-04",
            name = "Marian Road 500kVA Substation",
            street = "Marian Road, Calabar",
            city = "Calabar",
            state = "Cross River State",
            discoCode = "PHED",
            feederName = "Calabar Central 33kV",
            feederBand = FeederBand.BAND_B,
            latitude = 4.9757,
            longitude = 8.3417,
            capacityKva = 500,
            loadPercent = 67,
            phaseAVolts = 228,
            phaseBVolts = 225,
            phaseCVolts = 230,
            connectedHouseholds = 170,
            status = TransformerStatus.HEALTHY,
            oilTempCelsius = 58,
            humSparkRisk = "Nominal",
            failureCountMonth = 0,
            missingPartNotice = null
        )
    )
}
