package com.example.ui.solutions

import android.content.Context
import android.content.Intent
import android.net.Uri
import android.widget.Toast
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.AccountBalance
import androidx.compose.material.icons.filled.Calculate
import androidx.compose.material.icons.filled.CheckCircle
import androidx.compose.material.icons.filled.ContentCopy
import androidx.compose.material.icons.filled.Description
import androidx.compose.material.icons.filled.MoneyOff
import androidx.compose.material.icons.filled.Receipt
import androidx.compose.material.icons.filled.Warning
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.Icon
import androidx.compose.material3.LinearProgressIndicator
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.Slider
import androidx.compose.material3.SliderDefaults
import androidx.compose.material3.Surface
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalClipboardManager
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.AnnotatedString
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.example.model.UserProfile
import com.example.ui.theme.EmeraldAccent
import com.example.ui.theme.GoldPrimary

// ==========================================
// SOLUTION 11: AUTOMATED BAND AUDITOR
// ==========================================
@Composable
fun AutomatedBandAuditorFeature(
    userProfile: UserProfile,
    modifier: Modifier = Modifier
) {
    val context = LocalContext.current
    var actualDailyHours by remember { mutableStateOf(11.5f) }
    var petitionGenerated by remember { mutableStateOf(false) }

    val requiredHours = when (userProfile.feederBand.code) {
        "Band A" -> 20.0f
        "Band B" -> 16.0f
        "Band C" -> 12.0f
        else -> 8.0f
    }

    val deficitHours = (requiredHours - actualDailyHours).coerceAtLeast(0f)
    val shortfallPercent = ((deficitHours / requiredHours) * 100f).coerceIn(0f, 100f)
    val estimatedOverbillingNgn = (deficitHours * 30 * 45).toInt()

    Column(
        modifier = modifier.fillMaxWidth(),
        verticalArrangement = Arrangement.spacedBy(12.dp)
    ) {
        Text(
            text = "11. Automated Band Auditor (NERC SLA Enforcement)",
            style = MaterialTheme.typography.titleMedium,
            fontWeight = FontWeight.Bold,
            color = MaterialTheme.colorScheme.onSurface
        )
        Text(
            text = "Verifies if your DisCo delivered the minimum 20 hours/day for Band A. Calculates illegal tariff overbilling when supply falls short.",
            fontSize = 12.sp,
            color = MaterialTheme.colorScheme.onSurfaceVariant
        )

        Card(
            modifier = Modifier.fillMaxWidth(),
            shape = RoundedCornerShape(14.dp),
            colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.5f))
        ) {
            Column(modifier = Modifier.padding(14.dp), verticalArrangement = Arrangement.spacedBy(10.dp)) {
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.SpaceBetween,
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    Text("Contracted Tariff Band:", fontSize = 12.sp)
                    Surface(color = GoldPrimary.copy(alpha = 0.2f), shape = RoundedCornerShape(6.dp)) {
                        Text(userProfile.feederBand.code, fontWeight = FontWeight.Bold, color = GoldPrimary, fontSize = 11.sp, modifier = Modifier.padding(horizontal = 8.dp, vertical = 2.dp))
                    }
                }

                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.SpaceBetween
                ) {
                    Text("Actual Average Daily Supply Received:", fontSize = 11.sp)
                    Text("${String.format("%.1f", actualDailyHours)} Hours / Day", fontWeight = FontWeight.Bold, color = if (deficitHours > 0) MaterialTheme.colorScheme.error else EmeraldAccent, fontSize = 12.sp)
                }

                Slider(
                    value = actualDailyHours,
                    onValueChange = { actualDailyHours = it },
                    valueRange = 0f..24f,
                    colors = SliderDefaults.colors(thumbColor = GoldPrimary, activeTrackColor = GoldPrimary)
                )

                Surface(
                    color = if (deficitHours > 0) MaterialTheme.colorScheme.error.copy(alpha = 0.12f) else EmeraldAccent.copy(alpha = 0.12f),
                    shape = RoundedCornerShape(10.dp),
                    border = androidx.compose.foundation.BorderStroke(1.dp, if (deficitHours > 0) MaterialTheme.colorScheme.error else EmeraldAccent)
                ) {
                    Column(modifier = Modifier.padding(10.dp), verticalArrangement = Arrangement.spacedBy(4.dp)) {
                        Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                            Text("Statutory Supply Shortfall:", fontSize = 11.sp, fontWeight = FontWeight.SemiBold)
                            Text("${String.format("%.1f", deficitHours)} hrs (${shortfallPercent.toInt()}%)", fontWeight = FontWeight.Bold, color = MaterialTheme.colorScheme.error, fontSize = 11.sp)
                        }
                        Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                            Text("Estimated Monthly Tariff Overbilling:", fontSize = 11.sp, fontWeight = FontWeight.SemiBold)
                            Text("₦${estimatedOverbillingNgn}", fontWeight = FontWeight.Black, color = GoldPrimary, fontSize = 13.sp)
                        }
                    }
                }

                Button(
                    onClick = {
                        petitionGenerated = true
                        Toast.makeText(context, "Drafted NERC Band Demotion & Tariff Refund Petition!", Toast.LENGTH_SHORT).show()
                    },
                    colors = ButtonDefaults.buttonColors(containerColor = GoldPrimary, contentColor = Color.Black),
                    shape = RoundedCornerShape(10.dp),
                    modifier = Modifier.fillMaxWidth()
                ) {
                    Icon(Icons.Default.Description, contentDescription = null, modifier = Modifier.size(16.dp))
                    Spacer(modifier = Modifier.width(6.dp))
                    Text(if (petitionGenerated) "Petition Exported to NERC Desk ✓" else "Generate NERC Demotion & Refund Claim", fontWeight = FontWeight.Bold)
                }
            }
        }
    }
}

// ==========================================
// SOLUTION 12: AUTOMATED REFUND & SLA COMPENSATION LEDGER
// ==========================================
@Composable
fun AutomatedRefundLedgerFeature(
    userProfile: UserProfile,
    modifier: Modifier = Modifier
) {
    val context = LocalContext.current
    var outageDurationHours by remember { mutableStateOf(48f) }
    var claimSubmitted by remember { mutableStateOf(false) }

    val daysExceeded = ((outageDurationHours - 24f) / 24f).coerceAtLeast(0f)
    val statutoryPenaltyNgn = (daysExceeded * 2000f).toInt()
    val claimRef = "NERC-CPR-2026-${(1000..9999).random()}"

    Column(
        modifier = modifier.fillMaxWidth(),
        verticalArrangement = Arrangement.spacedBy(12.dp)
    ) {
        Text(
            text = "12. NERC CPR 2023 Compensation & Refund Ledger",
            style = MaterialTheme.typography.titleMedium,
            fontWeight = FontWeight.Bold,
            color = MaterialTheme.colorScheme.onSurface
        )
        Text(
            text = "Enforces NERC Customer Protection Regulations (CPR) 2023 Section 14: DisCos must pay automatic statutory rebates for prolonged unresolved outages.",
            fontSize = 12.sp,
            color = MaterialTheme.colorScheme.onSurfaceVariant
        )

        Card(
            modifier = Modifier.fillMaxWidth(),
            shape = RoundedCornerShape(14.dp),
            colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.5f))
        ) {
            Column(modifier = Modifier.padding(14.dp), verticalArrangement = Arrangement.spacedBy(10.dp)) {
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.SpaceBetween
                ) {
                    Text("Total Outage Duration:", fontSize = 11.sp)
                    Text("${outageDurationHours.toInt()} Consecutive Hours", fontWeight = FontWeight.Bold, color = GoldPrimary, fontSize = 12.sp)
                }

                Slider(
                    value = outageDurationHours,
                    onValueChange = { outageDurationHours = it },
                    valueRange = 12f..120f,
                    colors = SliderDefaults.colors(thumbColor = GoldPrimary, activeTrackColor = GoldPrimary)
                )

                Surface(
                    color = Color.Black.copy(alpha = 0.4f),
                    shape = RoundedCornerShape(10.dp),
                    modifier = Modifier.fillMaxWidth()
                ) {
                    Column(modifier = Modifier.padding(10.dp), verticalArrangement = Arrangement.spacedBy(6.dp)) {
                        Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                            Text("Statutory SLA Threshold:", fontSize = 11.sp, color = Color.Gray)
                            Text("Max 24 Hours", fontSize = 11.sp, color = Color.White)
                        }
                        Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                            Text("Days in Breach of Law:", fontSize = 11.sp, color = Color.Gray)
                            Text("${String.format("%.1f", daysExceeded)} Days", fontSize = 11.sp, color = MaterialTheme.colorScheme.error, fontWeight = FontWeight.Bold)
                        }
                        Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                            Text("DisCo Mandatory Compensation:", fontSize = 11.sp, color = Color.Gray)
                            Text("₦$statutoryPenaltyNgn", fontSize = 14.sp, color = EmeraldAccent, fontWeight = FontWeight.Black)
                        }
                    }
                }

                Button(
                    onClick = {
                        claimSubmitted = true
                        Toast.makeText(context, "Submitted $claimRef to ${userProfile.discoCode} Regulatory Escrow!", Toast.LENGTH_SHORT).show()
                    },
                    colors = ButtonDefaults.buttonColors(containerColor = GoldPrimary, contentColor = Color.Black),
                    shape = RoundedCornerShape(10.dp),
                    modifier = Modifier.fillMaxWidth()
                ) {
                    Icon(Icons.Default.AccountBalance, contentDescription = null, modifier = Modifier.size(16.dp))
                    Spacer(modifier = Modifier.width(6.dp))
                    Text(if (claimSubmitted) "Claim Filed to DisCo Escrow ✓" else "File NERC Statutory Refund Claim", fontWeight = FontWeight.Bold)
                }
            }
        }
    }
}

// ==========================================
// SOLUTION 13: COMMUNITY CONSUMPTION CALCULATOR
// ==========================================
@Composable
fun CommunityConsumptionCalculatorFeature(
    userProfile: UserProfile,
    modifier: Modifier = Modifier
) {
    val context = LocalContext.current
    val clipboardManager = LocalClipboardManager.current
    var estimatedBillNgn by remember { mutableStateOf(68000f) }
    val streetMeteredAverageNgn = 19200
    val illegalOverbillingMargin = (estimatedBillNgn - streetMeteredAverageNgn).coerceAtLeast(0f).toInt()

    Column(
        modifier = modifier.fillMaxWidth(),
        verticalArrangement = Arrangement.spacedBy(12.dp)
    ) {
        Text(
            text = "13. Community Consumption Auditor (Anti-Estimated Billing)",
            style = MaterialTheme.typography.titleMedium,
            fontWeight = FontWeight.Bold,
            color = MaterialTheme.colorScheme.onSurface
        )
        Text(
            text = "Scientific peer audit against 14 metered neighbors on your transformer to prove crazy estimated bills violate the NERC Capped Billing Order.",
            fontSize = 12.sp,
            color = MaterialTheme.colorScheme.onSurfaceVariant
        )

        Card(
            modifier = Modifier.fillMaxWidth(),
            shape = RoundedCornerShape(14.dp),
            colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.5f))
        ) {
            Column(modifier = Modifier.padding(14.dp), verticalArrangement = Arrangement.spacedBy(10.dp)) {
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.SpaceBetween
                ) {
                    Text("DisCo Estimated Bill Given:", fontSize = 11.sp)
                    Text("₦${estimatedBillNgn.toInt()}", fontWeight = FontWeight.Bold, color = MaterialTheme.colorScheme.error, fontSize = 13.sp)
                }

                Slider(
                    value = estimatedBillNgn,
                    onValueChange = { estimatedBillNgn = it },
                    valueRange = 10000f..150000f,
                    colors = SliderDefaults.colors(thumbColor = GoldPrimary, activeTrackColor = GoldPrimary)
                )

                Surface(
                    color = MaterialTheme.colorScheme.surfaceVariant,
                    shape = RoundedCornerShape(10.dp)
                ) {
                    Column(modifier = Modifier.padding(10.dp), verticalArrangement = Arrangement.spacedBy(6.dp)) {
                        Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                            Text("Neighbor Average (Metered, same feeder):", fontSize = 11.sp)
                            Text("₦$streetMeteredAverageNgn", fontWeight = FontWeight.Bold, color = EmeraldAccent, fontSize = 11.sp)
                        }
                        Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                            Text("Illegal Extortion Margin:", fontSize = 11.sp, fontWeight = FontWeight.Bold)
                            Text("+₦$illegalOverbillingMargin (${((illegalOverbillingMargin / streetMeteredAverageNgn.toFloat()) * 100).toInt()}%)", fontWeight = FontWeight.Black, color = MaterialTheme.colorScheme.error, fontSize = 12.sp)
                        }
                    }
                }

                Button(
                    onClick = {
                        val letter = "FORMAL DISPUTE: Capped Estimated Bill of ₦${estimatedBillNgn.toInt()} exceeds Street Metered Peer Average of ₦$streetMeteredAverageNgn under NERC Capped Billing Order Order/NERC/197/2020 on Transformer ${userProfile.transformerId}."
                        clipboardManager.setText(AnnotatedString(letter))
                        Toast.makeText(context, "Copied legal NERC dispute letter to clipboard!", Toast.LENGTH_SHORT).show()
                    },
                    colors = ButtonDefaults.buttonColors(containerColor = GoldPrimary, contentColor = Color.Black),
                    shape = RoundedCornerShape(10.dp),
                    modifier = Modifier.fillMaxWidth()
                ) {
                    Icon(Icons.Default.ContentCopy, contentDescription = null, modifier = Modifier.size(16.dp))
                    Spacer(modifier = Modifier.width(6.dp))
                    Text("Copy NERC Capped Billing Dispute Letter", fontWeight = FontWeight.Bold)
                }
            }
        }
    }
}

// ==========================================
// SOLUTION 14: METER WAITLIST TRACKER & HALL OF SHAME
// ==========================================
@Composable
fun MeterWaitlistTrackerFeature(
    userProfile: UserProfile,
    modifier: Modifier = Modifier
) {
    val context = LocalContext.current
    var daysWaiting by remember { mutableStateOf(26f) }
    val statutoryMaxDays = 10f
    val breachDays = (daysWaiting - statutoryMaxDays).coerceAtLeast(0f)
    val accumulatedPenaltyNgn = (breachDays * 2000f).toInt()

    Column(
        modifier = modifier.fillMaxWidth(),
        verticalArrangement = Arrangement.spacedBy(12.dp)
    ) {
        Text(
            text = "14. MAP Meter 10-Day Tracker & DisCo Hall of Shame",
            style = MaterialTheme.typography.titleMedium,
            fontWeight = FontWeight.Bold,
            color = MaterialTheme.colorScheme.onSurface
        )
        Text(
            text = "NERC mandates MAP meters must be installed within 10 working days of payment. Exposes DisCo delays and claims default fines.",
            fontSize = 12.sp,
            color = MaterialTheme.colorScheme.onSurfaceVariant
        )

        Card(
            modifier = Modifier.fillMaxWidth(),
            shape = RoundedCornerShape(14.dp),
            colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.5f))
        ) {
            Column(modifier = Modifier.padding(14.dp), verticalArrangement = Arrangement.spacedBy(10.dp)) {
                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.SpaceBetween
                ) {
                    Text("Days Since Meter Fee Payment:", fontSize = 11.sp)
                    Text("${daysWaiting.toInt()} Days", fontWeight = FontWeight.Bold, color = if (breachDays > 0) MaterialTheme.colorScheme.error else EmeraldAccent, fontSize = 12.sp)
                }

                Slider(
                    value = daysWaiting,
                    onValueChange = { daysWaiting = it },
                    valueRange = 1f..60f,
                    colors = SliderDefaults.colors(thumbColor = GoldPrimary, activeTrackColor = GoldPrimary)
                )

                Surface(
                    color = if (breachDays > 0) MaterialTheme.colorScheme.error.copy(alpha = 0.12f) else EmeraldAccent.copy(alpha = 0.12f),
                    shape = RoundedCornerShape(10.dp)
                ) {
                    Column(modifier = Modifier.padding(10.dp), verticalArrangement = Arrangement.spacedBy(4.dp)) {
                        Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                            Text("Statutory NERC Deadline:", fontSize = 11.sp)
                            Text("10 Working Days", fontSize = 11.sp, fontWeight = FontWeight.Bold)
                        }
                        Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                            Text("Days in Legal Breach:", fontSize = 11.sp)
                            Text("${breachDays.toInt()} Days", fontSize = 11.sp, fontWeight = FontWeight.Bold, color = MaterialTheme.colorScheme.error)
                        }
                        Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                            Text("Accrued Default Penalty:", fontSize = 11.sp)
                            Text("₦$accumulatedPenaltyNgn", fontSize = 13.sp, fontWeight = FontWeight.Black, color = GoldPrimary)
                        }
                    }
                }

                Text("DisCo Delay Ranking (Hall of Shame):", fontWeight = FontWeight.Bold, fontSize = 11.sp)
                Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                    Text("1. Kaduna Electric (42 days avg)", fontSize = 10.sp, color = MaterialTheme.colorScheme.error)
                    Text("2. Ikeja Electric (14 days)", fontSize = 10.sp, color = GoldPrimary)
                    Text("3. Eko DisCo (8 days)", fontSize = 10.sp, color = EmeraldAccent)
                }

                Button(
                    onClick = {
                        Toast.makeText(context, "Petitioned NERC Enforcement Division for default sanction!", Toast.LENGTH_SHORT).show()
                    },
                    colors = ButtonDefaults.buttonColors(containerColor = GoldPrimary, contentColor = Color.Black),
                    shape = RoundedCornerShape(10.dp),
                    modifier = Modifier.fillMaxWidth()
                ) {
                    Text("Petition NERC Enforcement on Meter Default", fontWeight = FontWeight.Bold)
                }
            }
        }
    }
}

// ==========================================
// SOLUTION 15: OFFLINE TOKEN VENDING VIA SMS/USSD
// ==========================================
@Composable
fun OfflineTokenVendingFeature(
    userProfile: UserProfile,
    modifier: Modifier = Modifier
) {
    val context = LocalContext.current
    val clipboardManager = LocalClipboardManager.current
    var selectedAmount by remember { mutableStateOf(5000) }
    var generatedToken by remember { mutableStateOf("4821 - 9023 - 1184 - 7629 - 0041") }
    var tokenCopied by remember { mutableStateOf(false) }

    val tariffPerKwh = 68.0 // approx standard
    val unitsKwh = (selectedAmount / tariffPerKwh)

    Column(
        modifier = modifier.fillMaxWidth(),
        verticalArrangement = Arrangement.spacedBy(12.dp)
    ) {
        Text(
            text = "15. Offline Prepaid Electricity Token Vending",
            style = MaterialTheme.typography.titleMedium,
            fontWeight = FontWeight.Bold,
            color = MaterialTheme.colorScheme.onSurface
        )
        Text(
            text = "Purchase 20-digit STS tokens with zero internet connection via bank telecom USSD gateways and input directly into your meter keypad.",
            fontSize = 12.sp,
            color = MaterialTheme.colorScheme.onSurfaceVariant
        )

        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.spacedBy(8.dp)
        ) {
            listOf(2000, 5000, 10000, 20000).forEach { amount ->
                val isSelected = selectedAmount == amount
                Button(
                    onClick = { selectedAmount = amount },
                    colors = ButtonDefaults.buttonColors(
                        containerColor = if (isSelected) GoldPrimary else MaterialTheme.colorScheme.surfaceVariant,
                        contentColor = if (isSelected) Color.Black else MaterialTheme.colorScheme.onSurface
                    ),
                    shape = RoundedCornerShape(8.dp),
                    modifier = Modifier.weight(1f)
                ) {
                    Text("₦$amount", fontSize = 10.sp, fontWeight = FontWeight.Bold)
                }
            }
        }

        Card(
            modifier = Modifier.fillMaxWidth(),
            shape = RoundedCornerShape(14.dp),
            colors = CardDefaults.cardColors(containerColor = MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.5f))
        ) {
            Column(modifier = Modifier.padding(14.dp), verticalArrangement = Arrangement.spacedBy(10.dp)) {
                Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                    Text("Target Meter Number:", fontSize = 11.sp)
                    Text(userProfile.meterNumber, fontWeight = FontWeight.Bold, color = GoldPrimary, fontSize = 12.sp)
                }
                Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                    Text("Calculated Electricity Units:", fontSize = 11.sp)
                    Text("${String.format("%.1f", unitsKwh)} kWh", fontWeight = FontWeight.Black, color = EmeraldAccent, fontSize = 13.sp)
                }

                Surface(
                    color = Color.Black.copy(alpha = 0.6f),
                    shape = RoundedCornerShape(10.dp),
                    modifier = Modifier.fillMaxWidth()
                ) {
                    Column(modifier = Modifier.padding(12.dp), horizontalAlignment = Alignment.CenterHorizontally, verticalArrangement = Arrangement.spacedBy(4.dp)) {
                        Text("20-Digit STS Prepaid Token:", fontSize = 10.sp, color = Color.Gray)
                        Text(generatedToken, fontFamily = FontFamily.Monospace, fontSize = 15.sp, fontWeight = FontWeight.Black, color = GoldPrimary)
                        Text("Type on Keypad and Press ↵ (Enter)", fontSize = 10.sp, color = Color.LightGray)
                    }
                }

                Row(
                    modifier = Modifier.fillMaxWidth(),
                    horizontalArrangement = Arrangement.spacedBy(8.dp)
                ) {
                    Button(
                        onClick = {
                            clipboardManager.setText(AnnotatedString(generatedToken.replace(" ", "").replace("-", "")))
                            tokenCopied = true
                            Toast.makeText(context, "Copied 20-digit token to clipboard!", Toast.LENGTH_SHORT).show()
                        },
                        colors = ButtonDefaults.buttonColors(containerColor = GoldPrimary, contentColor = Color.Black),
                        shape = RoundedCornerShape(8.dp),
                        modifier = Modifier.weight(1f)
                    ) {
                        Icon(Icons.Default.ContentCopy, contentDescription = null, modifier = Modifier.size(15.dp))
                        Spacer(modifier = Modifier.width(4.dp))
                        Text(if (tokenCopied) "Token Copied ✓" else "Copy Token", fontSize = 11.sp, fontWeight = FontWeight.Bold)
                    }

                    OutlinedButton(
                        onClick = {
                            val intent = Intent(Intent.ACTION_DIAL, Uri.parse("tel:*737*2*$selectedAmount*${userProfile.meterNumber}%23"))
                            context.startActivity(intent)
                        },
                        shape = RoundedCornerShape(8.dp),
                        modifier = Modifier.weight(1f)
                    ) {
                        Text("Bank USSD Pay", fontSize = 11.sp)
                    }
                }
            }
        }
    }
}
